"""Glossary content: (name, technical explanation, explanation for a child)."""

GLOSSARY = [
    ("P/E Ratio",
     "Price-to-Earnings = share price ÷ earnings per share (trailing 12 months). It shows how many dollars investors pay for $1 of yearly profit. Low can mean cheap (or a struggling company); high can mean growth expectations. Negative means the company lost money.",
     "Imagine a lemonade stand that makes $1 profit a year. If someone wants $20 to sell it to you, the P/E is 20. The bigger the number, the more you're paying for each dollar the stand earns."),
    ("Forward P/E",
     "Share price ÷ *expected* earnings per share over the next 12 months (analyst estimates). Useful for comparing to trailing P/E: if forward is lower, earnings are expected to grow.",
     "Same as P/E, but instead of looking at how much the lemonade stand made last year, we guess how much it will make next year."),
    ("PEG Ratio",
     "P/E ÷ expected annual earnings growth rate (in %). It adjusts P/E for growth. Around 1 is often seen as fairly priced; well below 1 may be cheap; above 2 may be expensive.",
     "A stand that costs a lot but is growing super fast may still be a good deal. PEG checks whether the price is fair *for how fast it's growing*."),
    ("P/S Ratio",
     "Price-to-Sales = market capitalization ÷ revenue over 12 months. Handy for companies with no profits yet. Lower is cheaper, but ignores margins.",
     "Instead of looking at the money left after paying bills, we look at all the money coming in from customers, and compare it to the price of the stand."),
    ("P/B Ratio",
     "Price-to-Book = share price ÷ book value per share (assets minus liabilities). Below 1 means the market values the company less than its accounting net worth. Less meaningful for asset-light tech companies.",
     "If you sold every table, cup and juicer the stand owns and paid its debts, you'd get some money. P/B compares the stand's price to that amount."),
    ("EV/EBITDA",
     "Enterprise Value ÷ EBITDA. EV = market cap + debt − cash. EBITDA = earnings before interest, taxes, depreciation and amortization. It compares companies regardless of debt levels and tax. Below ~10 is often seen as cheap.",
     "It asks: 'If I bought the whole stand AND took over its loans, how many years of its basic earnings would it take to pay me back?'"),
    ("ROE",
     "Return on Equity = net income ÷ shareholders' equity. Measures how efficiently a company turns investors' money into profit. Above 15% is generally strong.",
     "You give the stand $100 to grow. ROE tells you how many extra dollars it makes each year with your $100."),
    ("Profit Margin",
     "Net income ÷ revenue. The share of each sales dollar that ends up as profit. Higher margins mean more pricing power or efficiency.",
     "If you sell a lemonade for $1 and keep 20 cents after paying for everything, your margin is 20%."),
    ("Revenue Growth",
     "Year-over-year change in total sales. Growing revenue is a sign of expanding demand.",
     "Are more people buying lemonade this year than last year? By how much?"),
    ("Debt/Equity",
     "Total debt ÷ shareholders' equity. Shows how much the company relies on borrowed money. Higher means more financial risk, especially when interest rates rise. Norms vary a lot by industry (banks and utilities carry more).",
     "How much of the stand was paid for with borrowed money, compared to money the owners put in. Too much borrowing is risky."),
    ("Current Ratio",
     "Current assets ÷ current liabilities. Measures the ability to pay bills due within a year. Above 1.5 is comfortable; below 1 may signal liquidity stress.",
     "Do you have enough cash and lemons in the fridge to pay everything you owe this year?"),
    ("Expense Ratio",
     "The annual fee an ETF charges, as % of your invested amount (0.10% = $1 per $1,000 per year). It quietly reduces returns every year, so lower is better for similar funds.",
     "It's the small 'service fee' the basket-keeper takes every year for holding your stocks. A smaller fee means more money stays with you."),
    ("Fund Size (AUM)",
     "Assets Under Management: total money invested in the fund. Larger funds are usually easier to trade and less likely to close.",
     "How much money everyone has put in the basket together. A very popular basket is less likely to disappear."),
    ("1Y Return",
     "Price change over the last ~252 trading days (dividends reinvested where data allows). Past performance does not predict future results.",
     "If you had put $100 in one year ago, how many dollars would you have now?"),
    ("Volatility",
     "Annualized standard deviation of daily returns. Higher means bigger price swings and more risk. Roughly: 15% calm, 30%+ wild.",
     "How bumpy the roller coaster is. A calm ride goes up and down a little; a wild one throws you around."),
    ("Max Drawdown",
     "Largest peak-to-trough fall over the period. Shows the worst loss an investor would have suffered if buying at the top and selling at the bottom.",
     "The deepest dip on the roller coaster: how far it dropped from its highest point before climbing again."),
]
